create database QL_TAILIEUKH
USE QL_TAILIEUKH
create table TAIKHOAN(
	ID_TaiKhoan INT PRIMARY KEY NOT NULL,
	TenTaiKhoan VARCHAR(50),
	MatKhau VARCHAR(50)
);
create table NHAXUATBAN(
	ID_NhaXuatBan INT PRIMARY KEY NOT NULL,
	TenNhaXuatBan NVARCHAR(100)
);
create table HOINGHI(
	ID_HoiNghi INT PRIMARY KEY NOT NULL,
	TenHoiNghi NVARCHAR(100),
	NgayToChuc DATE,
	CapHoiNghi NVARCHAR(100),
	DiaDiem NVARCHAR(100)
); 
create table COQUANCHUQUAN(
	ID_CoQuanChuQuan INT PRIMARY KEY NOT NULL,
	TenCoQuanChuQuan NVARCHAR(100),
	LoaiCoQuan NVARCHAR(100),
	Khoa NVARCHAR(100)
);
create table NHAKHOAHOC(
	ID_NKH INT PRIMARY KEY NOT NULL,
	TenNhaKhoaHoc NVARCHAR(100),
	HocVi NVARCHAR(100),
	LinhVuc NVARCHAR(100),
	ID_TaiKhoan INT,
	FOREIGN KEY (ID_TaiKhoan) REFERENCES TAIKHOAN(ID_TaiKhoan)
);
create table VAITRO(
	ID_VaiTro INT PRIMARY KEY NOT NULL,
	TenVaiTro NVARCHAR(100)
);
create table TAILIEU(
	ID_TaiLieu INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	MoTa NVARCHAR(100),
	NamXuatBan DATE,
	LoaiTaiLieu NVARCHAR(100),
	ChuyenNganh NVARCHAR(100),
	NoiDung NVARCHAR(100),
	ID_TaiKhoan INT,
	FOREIGN KEY (ID_TaiKhoan) REFERENCES TAIKHOAN(ID_TaiKhoan)
);
create table CHITIETTAILIEU(
	ID_CTTaiLieu INT PRIMARY KEY NOT NULL,
	ID_TaiLieu INT,
	ID_NKH INT,
	ID_VaiTro INT,
	FOREIGN KEY (ID_TaiLieu) REFERENCES TAILIEU(ID_TaiLieu),
	FOREIGN KEY (ID_NKH) REFERENCES NHAKHOAHOC(ID_NKH),
	FOREIGN KEY (ID_VaiTro) REFERENCES VAITRO(ID_VaiTro)
);
create table BAIBAO(
	ID_BaiBao INT PRIMARY KEY NOT NULL,
	TenBaiBao NVARCHAR(100),
	NuocDangTai NVARCHAR(100),
	TomTat NVARCHAR(100),
	TuKhoa NVARCHAR(100),
	ID_TaiLieu INT NOT NULL,
	NoiDang NVARCHAR(100),
	FOREIGN KEY (ID_TaiLieu) REFERENCES TAILIEU(ID_TaiLieu)
);
create table GIAOTRINH(
	ID_GiaoTrinh INT PRIMARY KEY NOT NULL,
	ID_CoQuanChuQuan INT NOT NULL,
	TenGiaoTrinh NVARCHAR(100),
	NgayKyHopDong DATE,
	NgayKetThuc DATE,
	NoiDang NVARCHAR(100),
	ID_TaiLieu INT NOT NULL,
	FOREIGN KEY (ID_CoQuanChuQuan) REFERENCES COQUANCHUQUAN(ID_CoQuanChuQuan),
	FOREIGN KEY (ID_TaiLieu) REFERENCES TAILIEU(ID_TaiLieu)
);
create table TAPCHI(
	ID_TapChi INT PRIMARY KEY NOT NULL,
	ID_CoQuanChuQuan INT NOT NULL,
	ID_TaiLieu INT NOT NULL,
	TenTapChi NVARCHAR(100),
	KyDang NVARCHAR(100)
	FOREIGN KEY (ID_CoQuanChuQuan) REFERENCES COQUANCHUQUAN(ID_CoQuanChuQuan),
	FOREIGN KEY (ID_TaiLieu) REFERENCES TAILIEU(ID_TaiLieu)
);
create table CHITIETXUATBAN(
	ID_CTXUATBAN INT PRIMARY KEY NOT NULL,
	SoLuongXuatBan INT,
	ID_NhaXuatBan INT NOT NULL,
	ID_TapChi INT NOT NULL,
	FOREIGN KEY (ID_NhaXuatban) REFERENCES NHAXUATBAN(ID_NhaXuatBan),
	FOREIGN KEY (ID_TapChi) REFERENCES TAPCHI(ID_TapChi)
);
create table KYYEU(
	ID_KyYeu INT PRIMARY KEY NOT NULL,
	TenKyYeu NVARCHAR(100),
	ID_NhaXuatBan INT NOT NULL,
	ID_HoiNghi INT NOT NULL,
	ID_TaiLieu INT NOT NULL,
	FOREIGN KEY (ID_NhaXuatban) REFERENCES NHAXUATBAN(ID_NhaXuatBan),
	FOREIGN KEY (ID_TaiLieu) REFERENCES TAILIEU(ID_TaiLieu),
	FOREIGN KEY (ID_HoiNghi) REFERENCES HOINGHI(ID_HoiNghi)
);
create table DETAINCKH(
	ID_DeTaiNCKH INT PRIMARY KEY NOT NULL,
	ID_CoQuanChuQuan INT NOT NULL,
	ID_TaiLieu INT NOT NULL,
	TenDeTai NVARCHAR(100),
	CapDeTai NVARCHAR(100),
	LinhVucDeTai NVARCHAR(100),
	NoiDang NVARCHAR(100),
	FOREIGN KEY (ID_CoQuanChuQuan) REFERENCES COQUANCHUQUAN(ID_CoQuanChuQuan),
	FOREIGN KEY (ID_TaiLieu) REFERENCES TAILIEU(ID_TaiLieu)
);
